/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.connect;

/**
 *
 * @author phu
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btlKhachHang = new javax.swing.JButton();
        btlPhong = new javax.swing.JButton();
        btlThoat = new javax.swing.JButton();
        btlPhim = new javax.swing.JButton();
        btlVe = new javax.swing.JButton();
        btlLichChieu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btlKhachHang.setText("Khách hàng");
        btlKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlKhachHangActionPerformed(evt);
            }
        });

        btlPhong.setText("Phòng chiếu");
        btlPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlPhongActionPerformed(evt);
            }
        });

        btlThoat.setText("thoát");
        btlThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlThoatActionPerformed(evt);
            }
        });

        btlPhim.setText("Phim");
        btlPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlPhimActionPerformed(evt);
            }
        });

        btlVe.setText("Vé");
        btlVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlVeActionPerformed(evt);
            }
        });

        btlLichChieu.setText("Lịch chiếu");
        btlLichChieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlLichChieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btlKhachHang)
                    .addComponent(btlPhong)
                    .addComponent(btlPhim)
                    .addComponent(btlVe)
                    .addComponent(btlLichChieu))
                .addContainerGap(299, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btlThoat)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btlKhachHang)
                .addGap(18, 18, 18)
                .addComponent(btlPhong)
                .addGap(18, 18, 18)
                .addComponent(btlPhim)
                .addGap(18, 18, 18)
                .addComponent(btlVe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btlLichChieu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btlThoat)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btlThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlThoatActionPerformed
        // TODO add your handling code here:
                                    this.dispose();

            // Mở form Đăng nhập
            DangNhap dangNhapForm = new DangNhap(); 
            dangNhapForm.setVisible(true); 
    }//GEN-LAST:event_btlThoatActionPerformed

    private void btlKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlKhachHangActionPerformed
        // TODO add your handling code here:
            this.dispose();

            // Mở form Đăng nhập
            KhachHang khachHangForm = new KhachHang(); 
            khachHangForm.setVisible(true); 
    }//GEN-LAST:event_btlKhachHangActionPerformed

    private void btlPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlPhongActionPerformed
        // TODO add your handling code here:
            this.dispose();

            // Mở form 
            PhongChieu phongForm = new PhongChieu(); 
            phongForm.setVisible(true); 
    }//GEN-LAST:event_btlPhongActionPerformed

    private void btlPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlPhimActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Phim phimForm = new Phim();
        phimForm.setVisible(true);
    }//GEN-LAST:event_btlPhimActionPerformed

    private void btlVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlVeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Ve veForm = new Ve();
        veForm.setVisible(true);
    }//GEN-LAST:event_btlVeActionPerformed

    private void btlLichChieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlLichChieuActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LichChieu lichchieuForm = new LichChieu();
        lichchieuForm.setVisible(true);
    }//GEN-LAST:event_btlLichChieuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlKhachHang;
    private javax.swing.JButton btlLichChieu;
    private javax.swing.JButton btlPhim;
    private javax.swing.JButton btlPhong;
    private javax.swing.JButton btlThoat;
    private javax.swing.JButton btlVe;
    // End of variables declaration//GEN-END:variables
}
